apiVersion: v1
kind: Namespace
metadata:
  name: api
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-tool-config
  namespace: api
data:
  KEYCLOAK_REALM_URL: "http://keycloak-service.keycloak.svc.cluster.local:8080/realms/Demo"
  EXPECTED_AUDIENCE: "WeatherTool"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: weather-tool-sa
  namespace: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-tool
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-tool
  template:
    metadata:
      labels:
        app: weather-tool
    spec:
      serviceAccountName: weather-tool-sa
      containers:
      - name: weather-tool
        image: local/weather-tool:latest   # <-- build and push/tag your image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: weather-tool-config
---
apiVersion: v1
kind: Service
metadata:
  name: weather-tool
  namespace: api
spec:
  selector:
    app: weather-tool
  ports:
  - port: 5000
    targetPort: 5000
