# kind-cluster.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # Keycloak UI (later will run in cluster on 8080)
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      # SPIRE OIDC Discovery Provider (later will run in cluster on 8443)
      - containerPort: 30443
        hostPort: 30443
        protocol: TCP
